<a href="https://colab.research.google.com/github/Navisha-Kapil/Big-Dataa/blob/main/labeaval_group2_202301038.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
df = np.array([10,52,62,16,16,54,453])
s = np.sort(df)
print(s)

indices = np.argsort(df)
print(indices)

k = 4

print(s[:k])

m = 6

print(s[-m:])




[ 10  16  16  52  54  62 453]
[0 3 4 1 5 2 6]
[10 16 16 52]
[ 16  16  52  54  62 453]
